### ISSUE TITLE
Update home.ftl with HopN info

### ISSUE THREAD

**Issue by nicolelee24** [iJargon/HopN#12]
Will be bare bones for now until we find a template to use throughout pages.

**Comment by gretchy** [comment]
Things left to do:
   - change out template logo with our own (will be an image if time permits)
   - find a way to pull values for total number of users/events and display them
   - tidy up the footer by either adding or removing links

**Comment by gretchy** [comment]
all there's left to do is finding a way to pull values for total number of users/events and display them

**Comment by nicolelee24** [comment]
^^^ has been implemented, will show total numbers of users and events on home page
