### ISSUE TITLE
Split User and Events to separate pages

### ISSUE THREAD

**Issue by nicolelee24** [iJargon/HopN#13]
As of now, angular version for Events doesn't work.
Will have to do this using ftl.

Find a way to take the events info (delete/add/query) and move it to a new page (/event)

**Comment by nicolelee24** [comment]
1. Create event-control.js in js folder
2. Copy over event stuff from home-control.js on to ^
3. Create events.ftl in templates folder
4. Copy over event stuff from home.ftl on to ^
5. Edit WebController.java by adding ModelAndView getEventspage()
     "/cs480/events", add modelAndView Object of events list
     - remove the modelAndView Object of events from "/cs480/home"

**Comment by gretchy** [comment]
Eclipse wasn't able to see/open the newly created event-control.js so file was editted via Notepad++. Will need someone else to verify if event-control.js is viewable. Everything else was done as written via Eclipse.

**Comment by nicolelee24** [comment]
made a minor fix, but it works! good job!!
If you can't see a file, in eclipse, right-click and refresh the containing folder
