### ISSUE TITLE
//TODO: Make things pretty

### ISSUE THREAD

**Issue by nicolelee24** [iJargon/HopN#20]
- FaceBook links only work when logged in, switch to GitHub profile links
- In login page, align the purple paint brush somehow?
- In events page, move search event stuff above events list
- events page, change search button label from "Get" to "Search"
- events page, make "event ID, name, ..., end time table headers same size/font as the one for the search events (you can take out those headers outside of the dynamic parts
- events page, change add event button label from "Add" to "Create" and make to right of textfields

**Comment by nicolelee24** [comment]
Also format the profile.ftl page, i just created that one

**Comment by gretchy** [comment]
bullet point 5, making the header bold makes the entire "Events List" table bold when info other than the header shouldn't be bold
